### ISSUE TITLE
Comparison arguments inverted in `primitive <op> nodeset` case.

### ISSUE THREAD

**Issue by Parakleta** [google/wicked-good-xpath#26]
As seen in [binaryExpr.js](https://github.com/google/wicked-good-xpath/blob/1ca25201f66750bc24af05d165edac627e6c8b49/src/binaryExpr.js#L128-L152) where there is a primitive value and a nodeset, the nodeset is always passed as the first argument to the `comp` function.  This will obviously give the wrong result with the ordering comparisons ('<', '<=', '>', '>=').

**Comment by Dominator008** [comment]
This indeed looks like a bug.
