### ISSUE TITLE
How to use within Node and Browser

### ISSUE THREAD

**Issue by loretoparisi** [google/wicked-good-xpath#39]
I have downloaded the node source and required the module:

```javascript
XPath=require('./util/wgxpath');
XPath.install();
```

it gives no errors.
But now how to evaluate an available DOM and valid structure (supposed to have one within node)?

On a browser I have copied the install file in the Chrome `console` and the I did

```javascript
wgxpath.install()
```

But I cannot see there the `.test` object

```javascript
wgxpath.test
undefined
```

**Comment by Dominator008** [comment]
@loretoparisi Have you tried using `document.evaluate`? `wgxpath.test` is for testing the library and is not intended to be available.

**Comment by loretoparisi** [comment]
@Dominator008 ok for `document` evaluate in the browser, and what happens when in `node`?

**Comment by Dominator008** [comment]
You will need something like "jsdom" for that. Stealing the example from the third-party "node-wgxpath" NPM package: https://github.com/jacobmarble/node-wgxpath#example

**Comment by loretoparisi** [comment]
@Dominator008 amazing. I have html strings already, and I'm loading into a DOM object with `cheerio` like:

```javascript
  var $ = cheerio.load(html);
  var els = $('.content ul li')
```

so it should work like

```javascript
var document = cheerio.load(html);
wgxpath.install(document);
var expression = document.createExpression(expressionString);
var result = expression.evaluate(window.document,
wgxpath.XPathResultType.STRING_TYPE);
console.log('The Word of the Day is "' + result.stringValue + '."');
```

**Comment by Dominator008** [comment]
@loretoparisi Care to send a PR? :)

**Comment by loretoparisi** [comment]
@Dominator008 sure will do.

**Comment by Dominator008** [comment]
@loretoparisi https://github.com/jacobmarble/node-wgxpath#example hasn't been updated with 1.3.0. I have a pull request out as https://github.com/jacobmarble/node-wgxpath/pull/4 but it hasn't been merged yet.

**Comment by loretoparisi** [comment]
@Dominator008 thanks!
Since the pull request is already open, you can also update the example with the right expression:

```javascript
var url = 'http://www.merriam-webster.com/word-of-the-day';
var expressionString = '//*[@class="word-and-pronunciation"]/h1';
jsdom.env({
    url: url,
    done: function(errors, window) {
        wgxpath.install(window);
        var expression = window.document.createExpression(expressionString);
        var result = expression.evaluate(window.document,
            wgxpath.XPathResultType.STRING_TYPE);
        if (result.stringValue.length <= 0)
        console.log('Failed to get the word of the day.');
        else
        console.log('The Word of the Day is "' + result.stringValue + '."');

    }
});
```
