### ISSUE TITLE
Can't resolve anything but DIV in a specific scenario(JS FIDDLE Attached)

### ISSUE THREAD

**Issue by alexus2005** [google/wicked-good-xpath#52]
Hi guys,

Was using your wonderful library and unfortunately stumbled upon a specific xpath scenario where Google Chrome xpath resolver works fine, but Wicked Good Xpath fails to evaluate.

Basically in HTML structure like the one in JS Fiddle, nothing except DIV can be evaluated from the container.

Please tell me I am dumb and using it incorrectly :)

Please see the JS fiddle:
https://jsfiddle.net/xfwdybn7/

**Comment by ScottFreeCode** [comment]
How's this? https://jsfiddle.net/qnf6ko92/

**Comment by alexus2005** [comment]
Oh man, I had no idea that Xpath uses 1-based collection system. Totally my bad! Not an issue then! Sorry, and thank you!
